config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "genres#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :genres
  resources :directors
  resources :movies
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :favorite_genre, class_name: 'Genre'
  has_many :movie
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :director
  has_many :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :genre
  belongs_to :director
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
    @movies = Movie.where(director_id: @director.id)
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(director_params)

    if @director.save
      # flash.notice "As informações do diretor foram salvas com sucesso!"
      return redirect_to directors_path
    end

    render :new
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])

    if @director.update(director_params)
      # flash.notice "As informações do diretor foram atualizadas com sucesso!"
      return redirect_to directors_path
    end
  end

  # def destroy
  #   @director = Director.find(params[:id])
  #   @director.destroy
  #   redirect_to(new_director_path)
  # end

  private
  def director_params
    params.require(:director).permit(:name, :nationality, :birth_date, :favorite_genre_id)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @movies = Movie.where(genre_id: @genre.id)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      return redirect_to genres_path 
    end

    render :new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(genre_params)
      return redirect_to genres_path 
    end

    render :edit
  end

  # def destroy
  #   @genre = Genre.find(params[:id])
  #   @genre.destroy
  #   redirect_to(new_genre_path)
  # end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      return redirect_to movies_path 
    end

    render :new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      return redirect_to movie_path(@movie)
    end

    render :edit
  end

  # def destroy
  #   @movie = movie.find(params[:id])
  #   @movie.destroy
  #   redirect_to(new_movie_path)
  # end

  def movie_params
    params.require(:movie).permit(:title, :release_year, :synopsis, :origin, :duration, :genre_id, :director_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/directors/edit.html.erb
<h1> Editar Diretor </h1>

<%= form_with model: @director do |f| %>
  <div>
    <%= f.label "Nome"%><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label "Nacionalidade"%><br>
    <%= f.text_field :nationality %>
  </div>

  <div>
    <%= f.label "Data de nascimento"%><br>
    <%= f.date_select :birth_date ,
      start_year: 1900,
      end_year: Date.current.year %> 
  </div>

   <div>
    <%= f.label "Gênero favorito"%><br>
    <%= f.collection_select :favorite_genre_id, Genre.all, :id, :name %>
  </div>

  <div>
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/directors/index.html.erb
<h1> Lista de Diretores </h1>

<ul>
    <% @directors.each do |director| %>
        <li>
            <%= link_to director.name , director_path(director) %>
        </li>
    <% end %>
</ul>

<%= link_to "Novo diretor", new_director_path %>

app/views/directors/new.html.erb
<h1> Cadastro de Diretores </h1>
<%= form_with model: @director do |f| %>
  <div>
    <%= f.label "Nome"%><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label "Nacionalidade"%><br>
    <%= f.text_field :nationality %>
  </div>

  <div>
    <%= f.label "Data de nascimento"%><br>
    <%= f.date_select :birth_date,
      start_year: 1900,
      end_year: Date.current.year %>  

   <div>
    <%= f.label "Gênero favorito"%><br>
    <%= f.collection_select :favorite_genre_id, Genre.all, :id, :name %>
  </div>

  <div>
    <%= f.submit "Criar" %>
  </div>
<% end %>

app/views/directors/show.html.erb
<h3> Diretor: <%=@director.name %> </h3>
<h3> Nascimento: <%=@director.birth_date %> </h3>
<h3> Gênero favorito: <%= @director.favorite_genre.name %> </h3>


<%= link_to "Editar diretor", edit_director_path(@director)%>

<h2> Lista de filmes que são dirigdos por ele: </h2>

 <% @movies.each do |movie| %>
        <li>
            <%= link_to "#{movie.title} - #{movie.release_year}" , movie_path(movie) %>
        </li>
<% end %>

app/views/genres/edit.html.erb
<h1> Editar gênero </h1>
<%= form_with model: @genre do |f| %>
  <div>
    <%= f.label "Nome"%><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/genres/index.html.erb
<h1> Lista de Gêneros </h1>

<ul>
    <% @genres.each do |genre| %>
        <li>
            <%= link_to genre.name, genre_path(genre) %>
        </li>
    <% end %>
</ul>

<%= link_to "Novo gênero", new_genre_path %>

app/views/genres/new.html.erb
<h1> Cadastro de gênero </h1>
<%= form_with model: @genre do |f| %>
  <div>
    <%= f.label "Nome"%><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/genres/show.html.erb
<h1> Genero: <%=@genre.name %> </h1>

<%= link_to "Editar gênero", edit_genre_path(@genre)%>

<h1> Lista de filmes que são do gênero: <%=@genre.name %> </h1>

 <% @movies.each do |movie| %>
        <li>
            <%= link_to "#{movie.title} - #{movie.release_year}" , movie_path(movie) %>
        </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesCatalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to "Gêneros", genres_path %></li>
          <li><%= link_to "Diretores", directors_path %></li>
          <li><%= link_to "Filmes", movies_path %></li>
        </ul>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1> Editar filme </h1>
<%= form_with model: @movie do |f| %>
  <div>
    <%= f.label "Titulo"%><br>
    <%= f.text_field :title %>
  </div>

   <div>
    <%= f.label "Sinopse"%><br>
    <%= f.text_area :synopsis %>
  </div>

  <div>
    <%= f.label "Duração"%><br>
    <%= f.number_field :duration, min: 0, max: 500, step: 1 %>
  </div>

   <div>
    <%= f.label "Ano de lançamento"%><br>
    <%= f.number_field :release_year, min: 1500, step: 1, value: Date.current.year %>
  </div>

   <div>
    <%= f.label "Origem"%><br>
    <%= f.text_field :origin %>
  </div>

   <div>
    <%= f.label "Gênero"%><br>
     <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>

   <div>
     <%= f.label "Diretor"%><br>
     <%= f.collection_select :director_id, Director.all, :id, :name %>
  </div>

  <div>
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/movies/index.html.erb
<h1> Lista de Filmes </h1>

<ul>
    <% @movies.each do |movie| %>
        <li>
            <%= link_to "#{movie.title} - #{movie.release_year}" , movie_path(movie) %>
        </li>
    <% end %>
</ul>

<%= link_to "Novo filme", new_movie_path %>

app/views/movies/new.html.erb
<h1> Cadastro de filme </h1>

<%= form_with model: @movie do |f| %>
  <div>
    <%= f.label "Titulo"%><br>
    <%= f.text_field :title %>
  </div>

   <div>
    <%= f.label "Sinopse"%><br>
    <%= f.text_area :synopsis %>
  </div>

  <div>
    <%= f.label "Duração"%><br>
    <%= f.number_field :duration, min: 0, max: 500, step: 1 %>
  </div>

   <div>
    <%= f.label "Ano de lançamento"%><br>
    <%= f.number_field :release_year, min: 1500, step: 1, value: Date.current.year %>
  </div>

   <div>
    <%= f.label "Origem"%><br>
    <%= f.text_field :origin %>
  </div>

   <div>
    <%= f.label "Gênero"%><br>
     <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>

   <div>
     <%= f.label "Diretor"%><br>
     <%= f.collection_select :director_id, Director.all, :id, :name %>
  </div>

  <div>
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/movies/show.html.erb
<h1> Informações sobre o filme: </h1>

<h3> Titulo: <%= @movie.title %> </h3>
<h3> Genero: <%= @movie.genre.name %> </h3>
<h3> Sinopse: <%= @movie.synopsis %> </h3>
<h3> Ano de lançamento: <%= @movie.release_year %> </h3>
<h3> Duração: <%= @movie.duration %> </h3>
<h3> Diretor: <%= @movie.director.name %> </h3>
<h3> Origem: <%= @movie.origin %> </h3>

<%= link_to "Editar filme", edit_movie_path(@movie)%>